all:
  hosts:
    master-1:
      ansible_host: 158.160.53.101
      ip: 192.168.10.9
      access_ip: 158.160.53.101
      ansible_user: ubuntu
    worker-1:
      ansible_host: 158.160.104.245
      ip: 192.168.10.28
      access_ip: 158.160.104.245
      ansible_user: ubuntu
    worker-2:
      ansible_host: 158.160.52.241
      ip: 192.168.10.29
      access_ip: 158.160.52.241
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}